global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nginx-1-node'
    static_configs:
      - targets: ['nginx-1.ru-central1.internal:9100']

  - job_name: 'nginx-2-node'
    static_configs:
      - targets: ['nginx-2.ru-central1.internal:9100']

  - job_name: 'nginx-1_log_exporter'
    static_configs:
      - targets: ['nginx-1.ru-central1.internal:4040']

  - job_name: 'nginx-2_log_exporter'
    static_configs:
      - targets: ['nginx-2.ru-central1.internal:4040']

