version: '3.3'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./gfn.ini:/etc/grafana/grafana.ini
    environment:
      GF_PATHS_CONFIG: /etc/grafana/grafana.ini
    restart: always

volumes:
  grafana_data:

